#!/bin/sh

clear_trash() {
    local trash='.pytest_cache'
    [ -d "$trash" ] && echo "removing ${trash} testing trash" && rm -rf ${trash} && echo "environment is cleared"
}

clear_pyc() {
    find . -name '*.pyc' -delete && echo "removing pyc"
}

pip_install() {
    pip install -qr requirements.txt
}

run_tests() {
    pip_install
    pytest --codestyle -p no:warnings -vv tests
    clear_trash
    clear_pyc
}

run_tests
