#!/bin/sh

# python -m virtualenv env
# source env/bin/activate
# pip install
# ./run-tests

clear_trash() {
    local trash='.pytest_cache'
    [ -d "$trash" ] && echo "removing ${trash} testing trash" && rm -rf ${trash} && echo "environment is cleared"
}

clear_pyc() {
    find . -name '*.pyc' -delete && echo "removing pyc"
}

pip_install() {
    pip install -qr requirements.txt
}

run_tests() {
    pip_install
    pytest -p no:warnings -vv
    clear_trash
    clear_pyc
}

run_tests
